/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Regex.ValidacionFormReg;
import com.sun.awt.AWTUtilities;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rojeru_san.RSPanelsSlider;
import DAO.*;
import ClasesDTO.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Alonso
 */
public class MenuLogin_Reg extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MenuLogin_Reg() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
    }
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    UsuarioDTO usuarioDTO = new UsuarioDTO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        PanelInisioSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreoIS = new rojeru_san.RSMTextFull();
        txtPasswordIS = new rojeru_san.RSMPassView();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInicioSesion = new rojeru_san.RSButtonRiple();
        lblMensaje = new javax.swing.JLabel();
        PanelCarga = new javax.swing.JPanel();
        rSProgressMaterial1 = new rojerusan.componentes.RSProgressMaterial();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelRegistro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreReg = new rojeru_san.RSMTextFull();
        txtApellidoReg = new rojeru_san.RSMTextFull();
        txtCorreoReg = new rojeru_san.RSMTextFull();
        txtDireccionReg = new rojeru_san.RSMTextFull();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblMensajeRegistro = new javax.swing.JLabel();
        btnRegistro = new rojeru_san.RSButtonRiple();
        btnRegistro1 = new rojeru_san.RSButtonRiple();
        txtPasswordReg = new rojeru_san.RSMPassView();
        PanelRecuperar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCorreoRecu = new rojeru_san.RSMTextFull();
        jPanel5 = new javax.swing.JPanel();
        txtPwdRecu = new rojeru_san.RSMTextFull();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnParalogin2 = new rojeru_san.RSButtonRiple();
        btnRecuperar = new rojeru_san.RSButtonRiple();
        PanelDeBotones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnParalogin1 = new rojeru_san.RSButtonRiple();
        btnParaRegistro = new rojeru_san.RSButtonRiple();
        btnParaRecuperar = new rojeru_san.RSButtonRiple();
        btn_cerrar = new rojeru_san.RSButtonRiple();
        btn_cerrar1 = new rojeru_san.RSButtonRiple();
        btnInstagram = new rojeru_san.RSButtonRiple();
        btnFB = new rojeru_san.RSButtonRiple();
        btnYT = new rojeru_san.RSButtonRiple();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(953, 570));

        rSPanelsSlider1.setBackground(new java.awt.Color(204, 204, 204));

        PanelInisioSesion.setBackground(new java.awt.Color(204, 204, 204));
        PanelInisioSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        PanelInisioSesion.setName("PanelInisioSesion"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_user_120px.png"))); // NOI18N

        txtCorreoIS.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreoIS.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoIS.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtCorreoIS.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtCorreoIS.setBotonColor(new java.awt.Color(0, 0, 0));
        txtCorreoIS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCorreoIS.setModoMaterial(true);
        txtCorreoIS.setPlaceholder("Ingresa tu correo");

        txtPasswordIS.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordIS.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordIS.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtPasswordIS.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtPasswordIS.setBotonColor(new java.awt.Color(0, 0, 0));
        txtPasswordIS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPasswordIS.setModoMaterial(true);
        txtPasswordIS.setPlaceholder("Ingresa Password");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_user_male_40px.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_password_30px_2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INICIA TU SESIÓN");

        btnInicioSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.setColorHover(new java.awt.Color(102, 102, 102));
        btnInicioSesion.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelInisioSesionLayout = new javax.swing.GroupLayout(PanelInisioSesion);
        PanelInisioSesion.setLayout(PanelInisioSesionLayout);
        PanelInisioSesionLayout.setHorizontalGroup(
            PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInisioSesionLayout.createSequentialGroup()
                .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInisioSesionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelInisioSesionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelInisioSesionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreoIS, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(txtPasswordIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInisioSesionLayout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        PanelInisioSesionLayout.setVerticalGroup(
            PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInisioSesionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreoIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelInisioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasswordIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PanelInisioSesion, "card2");

        PanelCarga.setBackground(new java.awt.Color(204, 204, 204));
        PanelCarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanelCarga.setName("PanelCarga"); // NOI18N

        rSProgressMaterial1.setForeground(new java.awt.Color(51, 51, 51));
        rSProgressMaterial1.setAnchoProgress(15);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_time_120px.png"))); // NOI18N
        rSProgressMaterial1.add(jLabel17);
        jLabel17.setBounds(60, 60, 130, 120);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cargando ....");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¡Espere un momento, porfavor!");

        javax.swing.GroupLayout PanelCargaLayout = new javax.swing.GroupLayout(PanelCarga);
        PanelCarga.setLayout(PanelCargaLayout);
        PanelCargaLayout.setHorizontalGroup(
            PanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(PanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCargaLayout.createSequentialGroup()
                        .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCargaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCargaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(110, 110, 110))))
        );
        PanelCargaLayout.setVerticalGroup(
            PanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCargaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PanelCarga, "card3");

        PanelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        PanelRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanelRegistro.setName("PanelRegistro"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingresa tus datos para poder registrarte");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_add_administrator_80px_2.png"))); // NOI18N

        txtNombreReg.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreReg.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreReg.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtNombreReg.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtNombreReg.setBotonColor(new java.awt.Color(0, 0, 0));
        txtNombreReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombreReg.setModoMaterial(true);
        txtNombreReg.setPlaceholder("Ingresa tus nombres...");
        txtNombreReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreRegKeyTyped(evt);
            }
        });

        txtApellidoReg.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidoReg.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidoReg.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtApellidoReg.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtApellidoReg.setBotonColor(new java.awt.Color(0, 0, 0));
        txtApellidoReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellidoReg.setModoMaterial(true);
        txtApellidoReg.setPlaceholder("Ingresa tus apellidos...");
        txtApellidoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoRegKeyTyped(evt);
            }
        });

        txtCorreoReg.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreoReg.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreoReg.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtCorreoReg.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtCorreoReg.setBotonColor(new java.awt.Color(0, 0, 0));
        txtCorreoReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCorreoReg.setModoMaterial(true);
        txtCorreoReg.setPlaceholder("Ingresa tu correo...");

        txtDireccionReg.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccionReg.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccionReg.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtDireccionReg.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtDireccionReg.setBotonColor(new java.awt.Color(0, 0, 0));
        txtDireccionReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccionReg.setModoMaterial(true);
        txtDireccionReg.setPlaceholder("Ingresa tu dirección...");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Nombres     :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Apellidos     : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Correo         :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Password    :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Direccion    :");

        lblMensajeRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensajeRegistro.setForeground(new java.awt.Color(255, 51, 51));
        lblMensajeRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnRegistro.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRegistro.setText("Registrarme");
        btnRegistro.setColorHover(new java.awt.Color(102, 102, 102));
        btnRegistro.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnRegistro1.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_info_30px.png"))); // NOI18N
        btnRegistro1.setColorHover(new java.awt.Color(102, 102, 102));
        btnRegistro1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro1ActionPerformed(evt);
            }
        });

        txtPasswordReg.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordReg.setForeground(new java.awt.Color(51, 51, 51));
        txtPasswordReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasswordReg.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtPasswordReg.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtPasswordReg.setBotonColor(new java.awt.Color(0, 0, 0));
        txtPasswordReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPasswordReg.setModoMaterial(true);
        txtPasswordReg.setPlaceholder("Ingresa Password");

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDireccionReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtNombreReg, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                                    .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPasswordReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(txtCorreoReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addContainerGap())
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMensajeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensajeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PanelRegistro, "card4");

        PanelRecuperar.setBackground(new java.awt.Color(204, 204, 204));
        PanelRecuperar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanelRecuperar.setName("PanelRecuperar"); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_sync_120px.png"))); // NOI18N

        txtCorreoRecu.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreoRecu.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoRecu.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtCorreoRecu.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtCorreoRecu.setBotonColor(new java.awt.Color(0, 0, 0));
        txtCorreoRecu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCorreoRecu.setModoMaterial(true);
        txtCorreoRecu.setPlaceholder("Ingres tu correo");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        txtPwdRecu.setEditable(false);
        txtPwdRecu.setBackground(new java.awt.Color(204, 204, 204));
        txtPwdRecu.setForeground(new java.awt.Color(0, 0, 0));
        txtPwdRecu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPwdRecu.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtPwdRecu.setBordeColorNoFocus(new java.awt.Color(153, 153, 153));
        txtPwdRecu.setBotonColor(new java.awt.Color(0, 0, 0));
        txtPwdRecu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPwdRecu.setPlaceholder("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Password:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPwdRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPwdRecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ingresa tu correo y recupera tu clave");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("CORREO:");

        btnParalogin2.setBackground(new java.awt.Color(51, 51, 51));
        btnParalogin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnParalogin2.setText("Loguearse");
        btnParalogin2.setColorHover(new java.awt.Color(102, 102, 102));
        btnParalogin2.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnParalogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParalogin2ActionPerformed(evt);
            }
        });

        btnRecuperar.setBackground(new java.awt.Color(51, 51, 51));
        btnRecuperar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRecuperar.setText("Recuperar");
        btnRecuperar.setColorHover(new java.awt.Color(102, 102, 102));
        btnRecuperar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRecuperarLayout = new javax.swing.GroupLayout(PanelRecuperar);
        PanelRecuperar.setLayout(PanelRecuperarLayout);
        PanelRecuperarLayout.setHorizontalGroup(
            PanelRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRecuperarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnParalogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelRecuperarLayout.createSequentialGroup()
                .addGroup(PanelRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRecuperarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRecuperarLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelRecuperarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRecuperarLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelRecuperarLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreoRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(PanelRecuperarLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        PanelRecuperarLayout.setVerticalGroup(
            PanelRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRecuperarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoRecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnParalogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        rSPanelsSlider1.add(PanelRecuperar, "card5");

        PanelDeBotones.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_cake_120px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pastelería Nectar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bienvenido al Sistema");

        btnParalogin1.setBackground(new java.awt.Color(51, 51, 51));
        btnParalogin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnParalogin1.setText("Iniciar Sesión");
        btnParalogin1.setColorHover(new java.awt.Color(204, 204, 204));
        btnParalogin1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnParalogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParalogin1ActionPerformed(evt);
            }
        });

        btnParaRegistro.setBackground(new java.awt.Color(51, 51, 51));
        btnParaRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnParaRegistro.setText("Registrarse");
        btnParaRegistro.setColorHover(new java.awt.Color(204, 204, 204));
        btnParaRegistro.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnParaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaRegistroActionPerformed(evt);
            }
        });

        btnParaRecuperar.setBackground(new java.awt.Color(51, 51, 51));
        btnParaRecuperar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnParaRecuperar.setText("Recuperar Contraseña");
        btnParaRecuperar.setColorHover(new java.awt.Color(204, 204, 204));
        btnParaRecuperar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnParaRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnParalogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnParalogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnParaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelDeBotonesLayout = new javax.swing.GroupLayout(PanelDeBotones);
        PanelDeBotones.setLayout(PanelDeBotonesLayout);
        PanelDeBotonesLayout.setHorizontalGroup(
            PanelDeBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDeBotonesLayout.setVerticalGroup(
            PanelDeBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDeBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_cerrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/btn_cerrar.png"))); // NOI18N
        btn_cerrar.setColorHover(new java.awt.Color(102, 102, 102));
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_cerrar1.setBackground(new java.awt.Color(51, 51, 51));
        btn_cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_compress_30px_2.png"))); // NOI18N
        btn_cerrar1.setColorHover(new java.awt.Color(102, 102, 102));
        btn_cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar1ActionPerformed(evt);
            }
        });

        btnInstagram.setBackground(new java.awt.Color(204, 204, 204));
        btnInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_instagram_47px_1.png"))); // NOI18N
        btnInstagram.setColorHover(new java.awt.Color(153, 153, 153));
        btnInstagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstagramActionPerformed(evt);
            }
        });

        btnFB.setBackground(new java.awt.Color(204, 204, 204));
        btnFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_facebook_43px.png"))); // NOI18N
        btnFB.setColorHover(new java.awt.Color(153, 153, 153));
        btnFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFBActionPerformed(evt);
            }
        });

        btnYT.setBackground(new java.awt.Color(204, 204, 204));
        btnYT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/icons8_play_button_47px_1.png"))); // NOI18N
        btnYT.setColorHover(new java.awt.Color(153, 153, 153));
        btnYT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(PanelDeBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnYT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(btn_cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnYT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInstagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        usuarioDTO.setCorreo(txtCorreoIS.getText().trim());
        usuarioDTO.setPwd(txtPasswordIS.getText().trim());
        if (txtCorreoIS.getText().isEmpty() || txtPasswordIS.getText().isEmpty()) {
            lblMensaje.setText("¡Ingresar usuario y contraseña!");
        } else {
            if (usuarioDAO.userLogin(usuarioDTO)) {
                rSPanelsSlider1.setPanelSlider(1, PanelCarga, RSPanelsSlider.DIRECT.RIGHT);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Thread.sleep(1500);
                            dispose();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(MenuLogin_Reg.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                ).start();
            } else {
                lblMensaje.setText("¡Usuario y/o contraseña incorrecta!");
            }
        }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnParaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaRegistroActionPerformed
        rSPanelsSlider1.setPanelSlider(1, PanelRegistro, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnParaRegistroActionPerformed

    private void btnParalogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParalogin1ActionPerformed
        rSPanelsSlider1.setPanelSlider(1, PanelInisioSesion, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnParalogin1ActionPerformed

    private void btnParaRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaRecuperarActionPerformed
        rSPanelsSlider1.setPanelSlider(1, PanelRecuperar, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnParaRecuperarActionPerformed

    private void btnParalogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParalogin2ActionPerformed
        rSPanelsSlider1.setPanelSlider(1, PanelInisioSesion, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnParalogin2ActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar1ActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_cerrar1ActionPerformed

    private void btnInstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstagramActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI url = new java.net.URI("https://www.instagram.com/PasteleriaNectarC/");
                    desktop.browse(url);
                } catch (URISyntaxException ex) {
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_btnInstagramActionPerformed

    private void btnFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFBActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI url = new java.net.URI("https://www.facebook.com/Pasteler%C3%ADa-Nectar-C-113028920598719/");
                    desktop.browse(url);
                } catch (URISyntaxException ex) {
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_btnFBActionPerformed

    private void btnYTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYTActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI url = new java.net.URI("https://www.youtube.com/channel/UCLBdBy8RgKEVKSTGbl3g97g/?guided_help_flow=5");
                    desktop.browse(url);
                } catch (URISyntaxException ex) {
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_btnYTActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        if (txtNombreReg.getText().isEmpty() || txtApellidoReg.getText().isEmpty() || txtCorreoReg.getText().isEmpty() || txtPasswordReg.getText().isEmpty() || txtDireccionReg.getText().isEmpty()) {
            lblMensajeRegistro.setText("Asegurate de haber llenado todos los campos");
        } else {
            if (usuarioDAO.siExisteCorreo(txtCorreoReg.getText().trim())) {
                lblMensajeRegistro.setText("Ya existe el correo, ingrese otro");
            } else if(ValidacionFormReg.ValidaCorreo(txtCorreoReg.getText()) == true){
                lblMensajeRegistro.setText("Ingrese un correo válido");
            }else if (txtPasswordReg.getText().length() < 10 || txtPasswordReg.getText().length()>10) {
                lblMensajeRegistro.setText("La contraseña debe tener 10 carácteres");
            } else if (ValidacionFormReg.ValidaClave(txtPasswordReg.getText()) == true) {
                lblMensajeRegistro.setText("Formato de Password Incorrecto");
            } else {
                usuarioDTO.setNombre(txtNombreReg.getText().trim());
                usuarioDTO.setApellido(txtApellidoReg.getText().trim());
                usuarioDTO.setCorreo(txtCorreoReg.getText().trim());
                usuarioDTO.setPwd(txtPasswordReg.getText().trim());
                usuarioDTO.setDireccion(txtDireccionReg.getText().trim());
                usuarioDTO.setPerfil("Usuario");
                if (usuarioDAO.insert(usuarioDTO)) {
                    rSPanelsSlider1.setPanelSlider(1, PanelCarga, RSPanelsSlider.DIRECT.RIGHT);
                    lblMensajeRegistro.setText("");
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            try {
                                Thread.sleep(2000);
                                rSPanelsSlider1.setPanelSlider(1, PanelRegistro, RSPanelsSlider.DIRECT.RIGHT);
                                AvisoExito AExito = new AvisoExito();
                                AExito.setBounds(640, 435, 507, 219);
                                AExito.setVisible(true);
                                limpiarFrmReg();
                            } catch (InterruptedException ex) {
                                Logger.getLogger(MenuLogin_Reg.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    ).start();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar usuario");
                }
            }
        }


    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        usuarioDTO.setCorreo(txtCorreoRecu.getText().trim());
        if (usuarioDAO.Recuperar(usuarioDTO)) {
            txtPwdRecu.setText("" + usuarioDTO.getPwd());
        }
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void btnRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro1ActionPerformed
        AvisoRegex ARegex = new AvisoRegex();
        ARegex.setBounds(750, 335, 377, 345);
        ARegex.setVisible(true);
    }//GEN-LAST:event_btnRegistro1ActionPerformed

    private void txtNombreRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreRegKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {//si es digitos numericos
            getToolkit().beep();
            evt.consume();
            lblMensajeRegistro.setText("Ingrese Nombres válido");
        } 
    }//GEN-LAST:event_txtNombreRegKeyTyped

    private void txtApellidoRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoRegKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {//si es digitos numericos
            getToolkit().beep();
            evt.consume();
            lblMensajeRegistro.setText("Ingrese Apellidos válido");
    }//GEN-LAST:event_txtApellidoRegKeyTyped
    }

    void limpiarFrmReg() {
        txtNombreReg.setText("");
        txtApellidoReg.setText("");
        txtCorreoReg.setText("");
        txtPasswordReg.setText("");
        txtDireccionReg.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin_Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCarga;
    private javax.swing.JPanel PanelDeBotones;
    private javax.swing.JPanel PanelInisioSesion;
    private javax.swing.JPanel PanelRecuperar;
    private javax.swing.JPanel PanelRegistro;
    private rojeru_san.RSButtonRiple btnFB;
    private rojeru_san.RSButtonRiple btnInicioSesion;
    private rojeru_san.RSButtonRiple btnInstagram;
    private rojeru_san.RSButtonRiple btnParaRecuperar;
    private rojeru_san.RSButtonRiple btnParaRegistro;
    private rojeru_san.RSButtonRiple btnParalogin1;
    private rojeru_san.RSButtonRiple btnParalogin2;
    private rojeru_san.RSButtonRiple btnRecuperar;
    private rojeru_san.RSButtonRiple btnRegistro;
    private rojeru_san.RSButtonRiple btnRegistro1;
    private rojeru_san.RSButtonRiple btnYT;
    private rojeru_san.RSButtonRiple btn_cerrar;
    private rojeru_san.RSButtonRiple btn_cerrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensajeRegistro;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.componentes.RSProgressMaterial rSProgressMaterial1;
    private rojeru_san.RSMTextFull txtApellidoReg;
    private rojeru_san.RSMTextFull txtCorreoIS;
    private rojeru_san.RSMTextFull txtCorreoRecu;
    private rojeru_san.RSMTextFull txtCorreoReg;
    private rojeru_san.RSMTextFull txtDireccionReg;
    private rojeru_san.RSMTextFull txtNombreReg;
    private rojeru_san.RSMPassView txtPasswordIS;
    private rojeru_san.RSMPassView txtPasswordReg;
    private rojeru_san.RSMTextFull txtPwdRecu;
    // End of variables declaration//GEN-END:variables
}
